using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;

public static class FunctionChecker
{
    public static bool check(string stringToCheck) {
        if (functionList.Any(stringToCheck.Contains)) {
            return true;
        }
        else {
            return false;
        }
    }

    public static string[] getList() {
        return functionList;
    }

    private static string[] functionList = {":boolean_and",
                                            ":boolean_deep_dup",
                                            ":boolean_dup", 
                                            ":boolean_dup_items", 
                                            ":boolean_dup_times", 
                                            ":boolean_empty", 
                                            ":boolean_eq", 
                                            ":boolean_flush", 
                                            ":boolean_from_integer", 
                                            ":boolean_invert_first_then_and", 
                                            ":boolean_invert_second_then_and", 
                                            ":boolean_not", 
                                            ":boolean_or", 
                                            ":boolean_pop", 
                                            ":boolean_rot", 
                                            ":boolean_shove", 
                                            ":boolean_stack_depth", 
                                            ":boolean_swap", 
                                            ":boolean_xor", 
                                            ":boolean_yank", 
                                            ":boolean_yank_dup",
                                            ":exec_deep_dup", 
                                            ":exec_do_count", 
                                            ":exec_do_range", 
                                            ":exec_do_times", 
                                            ":exec_do_while", 
                                            ":exec_dup",
                                            ":exec_dup_items", 
                                            ":exec_dup_times", 
                                            ":exec_empty", 
                                            ":exec_eq", 
                                            ":exec_flush",
                                            ":exec_if", 
                                            ":exec_k", 
                                            ":exec_pop", 
                                            ":exec_rot", 
                                            ":exec_s", 
                                            ":exec_shove", 
                                            ":exec_stack_depth", 
                                            ":exec_swap", 
                                            ":exec_when", 
                                            ":exec_while", 
                                            ":exec_y", 
                                            ":exec_yank", 
                                            ":exec_yank_dup", 
                                            ":integer_add", 
                                            ":integer_dec", 
                                            ":integer_deep_dup", 
                                            ":integer_dup", 
                                            ":integer_dup_items", 
                                            ":integer_dup_times", 
                                            ":integer_empty", 
                                            ":integer_eq", 
                                            ":integer_flush", 
                                            ":integer_from_boolean", 
                                            ":integer_from_string", 
                                            ":integer_gt", 
                                            ":integer_gte", 
                                            ":integer_inc", 
                                            ":integer_lt", 
                                            ":integer_lte", 
                                            ":integer_max", 
                                            ":integer_min", 
                                            ":integer_mod", 
                                            ":integer_mult", 
                                            ":integer_pop", 
                                            ":integer_quot", 
                                            ":integer_rot", 
                                            ":integer_shove", 
                                            ":integer_stack_depth", 
                                            ":integer_subtract",
                                            ":integer_swap", 
                                            ":integer_yank", 
                                            ":integer_yank_dup", 
                                            ":string_butlast", 
                                            ":string_concat", 
                                            ":string_contains", 
                                            ":string_deep_dup", 
                                            ":string_drop", 
                                            ":string_dup", 
                                            ":string_dup_items", 
                                            ":string_dup_times", 
                                            ":string_empty", 
                                            ":string_empty_string", 
                                            ":string_eq", 
                                            ":string_flush", 
                                            ":string_from_boolean", 
                                            ":string_from_integer", 
                                            ":string_length", 
                                            ":string_parse_to_chars", 
                                            ":string_pop", 
                                            //":string_replace", 
                                            //":string_replace_first", 
                                            ":string_rest", 
                                            ":string_reverse", 
                                            ":string_rot", 
                                            ":string_shove", 
                                            //":string_split", 
                                            ":string_stack_depth",
                                            //":string_substr", 
                                            ":string_swap", 
                                            ":string_take", 
                                            ":string_yank", 
                                            ":string_yank_dup",
                                            };
}
